title: SwarmBender
description: A CLI to compose, render and manage secrets for Docker Swarm.
theme: jekyll-theme-minimal

url: "https://fusapp.github.io"
baseurl: "/SwarmBender"

logo: /SwarmBender/assets/logo.svg
show_downloads: false

plugins:
  - jekyll-seo-tag