name: Docs (GitHub Pages without external actions)

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - '.github/workflows/pages.yml'

permissions:
  contents: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (no external action)
        run: |
          git init .
          git remote add origin https://github.com/${{ github.repository }}.git
          git fetch --depth=1 origin ${{ github.sha }}
          git checkout --detach ${{ github.sha }}

      - name: Prepare docs
        run: |
          mkdir -p docs
          touch docs/.nojekyll
          # Eğer sadece index.md varsa, en basit fallback olarak yönlendirme koy.
          if [ ! -f docs/index.html ] && [ -f docs/index.md ]; then
            echo "<meta http-equiv='refresh' content='0; url=index.md'/>" > docs/index.html
          fi

      - name: Publish to gh-pages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          rm -rf out && mkdir out
          cp -R docs/* out/ || true
          cd out
          git init
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Publish docs for $GITHUB_SHA"
          git branch -M gh-pages
          git push -f https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git gh-pages